name: .NET Build 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.2.0
      
      - name: Run test
        run: 'bash -c "test.sh"'

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport # Artifact name        
          path: tests/Quartz.Spi.MongoDbJobStore.Tests/coveragereport # Directory containing files to upload