name: .NET Test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.2.0
      
      - name: Run test
        shell: bash
        run: |
          docker-compose -p mongo_quartz down 
          docker-compose -p mongo_quartz rm
          docker-compose -p mongo_quartz build
          docker-compose -p mongo_quartz up -d
          docker wait $(docker ps -aqf "name=myapp_mongo_quartz")
      - name: Clean up docker
        run: |
          docker-compose -p mongo_quartz down 
          docker-compose -p mongo_quartz rm
          
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport # Artifact name        
          path: tests/Quartz.Spi.MongoDbJobStore.Tests/coveragereport # Directory containing files to upload